In [ ]:
# 🍔 FoodSense: Data Cleaning & ETL Process

#This notebook focuses on loading, understanding, and cleaning the food ordering behavior dataset as part of the ETL process.

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\anshi\Desktop\FoodSENSE;Costomer_behaviour_intelligence_for_food_delivery\food_ordering_behavior_dataset.csv")
df.head()

,order_id,user_id,age,city,order_time,day_type,cuisine,meal_type,restaurant_type,order_value,discount_applied,delivery_fee,time_taken_to_order,rating_given,is_repeat_order,mood,hunger_level,company,rainy_weather
0,1,2698,35,pune,evening,weekend,chinese,dinner,premium,971,yes,90,13,1,yes,celebrating,high,partner,no
1,2,3237,44,mumbai,night,weekend,south indian,dinner,budget,442,no,26,13,2,no,lazy,low,family,no
2,3,3626,31,delhi,morning,weekend,biryani,breakfast,mid-range,739,yes,85,10,2,yes,happy,medium,friends,no
3,4,3176,23,delhi,evening,weekend,biryani,snacks,mid-range,466,no,44,12,2,no,happy,medium,alone,no
4,5,4824,26,chandigarh,morning,weekday,chinese,lunch,premium,927,yes,58,13,2,no,happy,medium,partner,yes

In [2]:
## 🔍 Data Understanding

'''In this step, the structure and quality of the dataset are explored to understand:
- Number of rows and columns
- Data types
- Statistical summary
- Missing values'''

'In this step, the structure and quality of the dataset are explored to understand:\n- Number of rows and columns\n- Data types\n- Statistical summary\n- Missing values'

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             50000 non-null  int64
 1   user_id              50000 non-null  int64
 2   age                  50000 non-null  int64
 3   city                 50000 non-null  object
 4   order_time           50000 non-null  object
 5   day_type             50000 non-null  object
 6   cuisine              50000 non-null  object
 7   meal_type            50000 non-null  object
 8   restaurant_type      50000 non-null  object
 9   order_value          50000 non-null  int64
 10  discount_applied     50000 non-null  object
 11  delivery_fee         50000 non-null  int64
 12  time_taken_to_order  50000 non-null  int64
 13  rating_given         50000 non-null  int64
 14  is_repeat_order      50000 non-null  object
 15  mood                 50000 non-null  object
 16  hunger_level         50000 non-null  object
 17  company              50000 non-null  object
 18  rainy_weather        50000 non-null  object
dtypes: int64(7), object(12)
memory usage: 7.2+ MB

In [5]:
## 📊 Statistical Summary

'''This step provides statistical insights into numerical columns such as:
- Mean
- Minimum and maximum values
- Distribution of data

It helps in understanding the overall behavior of numerical features.'''
df.describe()

,order_id,user_id,age,order_value,delivery_fee,time_taken_to_order,rating_given
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,25000.500000,3005.466160,30.975420,547.731100,59.642720,7.496720,2.994420
std,14433.901067,1152.286323,7.804962,259.685968,23.043375,4.031059,1.413361
min,1.000000,1000.000000,18.000000,100.000000,20.000000,1.000000,1.000000
25%,12500.750000,2013.000000,24.000000,323.000000,40.000000,4.000000,2.000000
50%,25000.500000,3004.000000,31.000000,547.000000,60.000000,7.000000,3.000000
75%,37500.250000,4002.000000,38.000000,772.000000,80.000000,11.000000,4.000000
max,50000.000000,4999.000000,44.000000,999.000000,99.000000,14.000000,5.000000

In [6]:
## 🏷️ Column Inspection

#In this step, all column names are reviewed to understand the available features in the dataset.

#This helps in planning further analysis and identifying important business-related variables.

In [9]:
df.columns

Index(['order_id', 'user_id', 'age', 'city', 'order_time', 'day_type',
       'cuisine', 'meal_type', 'restaurant_type', 'order_value',
       'discount_applied', 'delivery_fee', 'time_taken_to_order',
       'rating_given', 'is_repeat_order', 'mood', 'hunger_level', 'company',
       'rainy_weather'],
      dtype='object')

In [10]:
## ❗ Missing Value Analysis

'''This step checks whether the dataset contains any missing or null values.

Handling missing values is important to maintain data quality and ensure accurate analysis.'''

'This step checks whether the dataset contains any missing or null values.\n\nHandling missing values is important to maintain data quality and ensure accurate analysis.'

In [12]:
df.isnull().sum()

order_id               0
user_id                0
age                    0
city                   0
order_time             0
day_type               0
cuisine                0
meal_type              0
restaurant_type        0
order_value            0
discount_applied       0
delivery_fee           0
time_taken_to_order    0
rating_given           0
is_repeat_order        0
mood                   0
hunger_level           0
company                0
rainy_weather          0
dtype: int64

In [13]:
## 🔁 Duplicate Record Check

'''This step checks whether duplicate records exist in the dataset.

Duplicate rows can negatively impact analysis and lead to misleading insights.'''

'This step checks whether duplicate records exist in the dataset.\n\nDuplicate rows can negatively impact analysis and lead to misleading insights.'

In [14]:
df.duplicated().sum()

0

In [15]:
## 🧹 Text Standardization

'''In this step, categorical text values are standardized by converting them to lowercase.

This helps maintain consistency in the dataset and prevents incorrect grouping during analysis.'''

'In this step, categorical text values are standardized by converting them to lowercase.\n\nThis helps maintain consistency in the dataset and prevents incorrect grouping during analysis.'

In [16]:
df = df.apply(lambda x: x.str.lower() if x.dtype == "object" else x)

df.head()

,order_id,user_id,age,city,order_time,day_type,cuisine,meal_type,restaurant_type,order_value,discount_applied,delivery_fee,time_taken_to_order,rating_given,is_repeat_order,mood,hunger_level,company,rainy_weather
0,1,2698,35,pune,evening,weekend,chinese,dinner,premium,971,yes,90,13,1,yes,celebrating,high,partner,no
1,2,3237,44,mumbai,night,weekend,south indian,dinner,budget,442,no,26,13,2,no,lazy,low,family,no
2,3,3626,31,delhi,morning,weekend,biryani,breakfast,mid-range,739,yes,85,10,2,yes,happy,medium,friends,no
3,4,3176,23,delhi,evening,weekend,biryani,snacks,mid-range,466,no,44,12,2,no,happy,medium,alone,no
4,5,4824,26,chandigarh,morning,weekday,chinese,lunch,premium,927,yes,58,13,2,no,happy,medium,partner,yes

In [17]:
## 💾 Saving Cleaned Dataset

'''The cleaned dataset is saved for further analysis and visualization.

This cleaned data will be used in:
- Exploratory Data Analysis (EDA)
- SQL Analysis
- Power BI Dashboard'''

'The cleaned dataset is saved for further analysis and visualization.\n\nThis cleaned data will be used in:\n- Exploratory Data Analysis (EDA)\n- SQL Analysis\n- Power BI Dashboard'

In [19]:
df.to_csv(r"C:\Users\anshi\Desktop\FoodSENSE;Costomer_behaviour_intelligence_for_food_delivery\cleaned_data.csv", index=False)